CREATE ROLE Prakriti WITH LOGIN PASSWORD 'prak@123'

GRANT USAGE ON SCHEMA inventory TO Prakriti;
GRANT SELECT, INSERT, UPDATE, DELETE 
ON ALL TABLES IN SCHEMA inventory
TO Prakriti; 

REVOKE ALL PRIVILEGES ON SCHEMA inventory FROM prakriti;
REVOKE USAGE ON SCHEMA inventory FROM prakriti;

DROP OWNED BY Prakriti;
DROP ROLE Prakriti;